# 主色调蓝色： #0084ff
# hover：     #006bde
# onerror="javascript:this.src='{{ with $.Site.Params.cdnURL }}{{ . }}{{ end }}{{ $.Site.Params.defaultLogo }}'"

baseURL               = "https://dy.202802.xyz/"
languageCode          = "zh-CN"
title                 = "驼铃电商工具箱"
theme                 = "webstack"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"	# 站点静态文件保存目录


[params]
    author        = "TLS"
    keywords      = "驼铃电商工具箱，驼铃电商百宝箱，驼铃百宝箱，驼铃工具箱，电商百宝箱，电商工具箱，助力商家更好的运营管理店铺"
    description   = "驼铃电商工具箱，驼铃电商百宝箱，驼铃工具箱，电商百宝箱，电商工具箱"
    cdnURL        = ""                                     # CDN 地址，置空则不使用 CDN
    cdnURLPubilc  = ""                                     # CDN 地址，置空则不使用 CDN
    repository    = "https://github.com/TLS-802"           # 左侧导航栏的"GitHub"
    enablePreLoad = true					               # 网站完全打开前预加载动画
    textPreLoad   = "驼铃电商工具箱 加载中."				  # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					               # 默认展开左侧边导航栏（已失效，默认不展开，会记住用户的行为，下次打开会保持）
    logosPath     = ""			                           # 网站每个导航地址logo存放地址（留空，因为YAML中已包含完整路径）
    defaultLogo   = "images/logo.png"		               # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					               # 默认站点为深色(夜间)模式
    yiyan         = true                         		   # 默认启用一言服务

[params.seo]    
    baiduhmid     = ""     # 百度统计 hm.src 的 ID（已禁用）
    baiduSiteVer  = "codeva-cnyCL4azyb"				       # 百度HTML标签验证(baidu-site-verification)
    tj51laid      = ""                     # 51.LA 网站统计（已禁用）
    tj51lack      = ""

[params.seniverse]
    key = "a39cd5a0-4024-4cb2-85c6-0250317058db"

[params.images]
    favicon           = "favicon.ico"
    appleTouchIcon    = "favicon.png"
    searchImageL      = ""		# 搜索部分浅色背景图（已禁用）
    searchImageD      = ""		    # 搜索部分深色背景图（已禁用）
    logoExpandLight   = "logo.png"
    logoExpandDark    = "logo.png"
    logoCollapseLight = "favicon.png"
    logoCollapseDark  = "favicon.png"

[params.info]
    email = "admin@itbob.cn"
    emailHref = "mailto:admin@itbob.cn"

[markup.goldmark.renderer]
    unsafe = true

[minify]
    minifyOutput = true
