name: Run Article Data To Yml Script

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 选择 GitHub 提供的运行环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 安装依赖包
      - name: Install dependencies
        run: |
          cd script
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行 Python 脚本
      - name: Run Python script
        run: |
          cd script
          python article_data_to_yml.py
        env:
          ARTICLE_API: ${{ secrets.ARTICLE_API }}
          ARTICLE_TOKEN: ${{ secrets.ARTICLE_TOKEN }}
