name: Run Article Data To Yml Script

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 选择 GitHub 提供的运行环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 安装依赖包
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./script

      # 运行 Python 脚本
      - name: Run Python script
        run: |
          pwd
          python article_data_to_yml.py
        env:
          ARTICLE_API: ${{ secrets.ARTICLE_API }}
          ARTICLE_TOKEN: ${{ secrets.ARTICLE_TOKEN }}
        working-directory: ./script

      - name: List all files in data directory
        run: |
          echo "Listing files in data directory:"
          ls -l
        working-directory: ./data

      # 检查是否有更改
      - name: Check if need to commit
        id: check_changes
        run: |
          pwd
          git diff --exit-code articles.yml || echo "File has been updated"
        working-directory: ./data

      # 提交并推送更改，使用 GitHub Token 进行认证
      - name: Commit updated article.yml and push to repository
        if: steps.check_changes.outputs.changed == 'true'  # 只有在有更改时才执行提交操作
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/articles.yml
          git commit -m "Update article.yml if data has changed"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
